-- This CLP file was created using DB2LOOK Version "9.7" 
-- Timestamp: 13-04-2013 16:55:36
-- Database Name: CMC            
-- Database Manager Version: DB2/NT Version 9.7.5          
-- Database Codepage: 1208
-- Database Collating Sequence is: IDENTITY


CONNECT TO CMC;

------------------------------------
-- DDL Statements for TABLESPACES --
------------------------------------


CREATE LARGE TABLESPACE "SYSTOOLSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE USER TEMPORARY TABLESPACE "SYSTOOLSTMPSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


-- Mimic tablespace

ALTER TABLESPACE SYSCATSPACE
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      NO FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000;


ALTER TABLESPACE TEMPSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      FILE SYSTEM CACHING 
      TRANSFERRATE 0.060000;


ALTER TABLESPACE USERSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      NO FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000;




------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."ACTIVATION"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."ACTIVATION"  (
		  "USERNAME" VARCHAR(20) NOT NULL , 
		  "ACTIVATION" VARCHAR(10) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."ACTIVATION"

ALTER TABLE "DB2ADMIN"."ACTIVATION" 
	ADD CONSTRAINT "CC1364469166636" PRIMARY KEY
		("USERNAME");


------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."FRIENDSHIP"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."FRIENDSHIP"  (
		  "FRIENDNAME" VARCHAR(50) NOT NULL , 
		  "USERNAME" VARCHAR(50) NOT NULL , 
		  "STATUS" CHAR(1) NOT NULL WITH DEFAULT '0' )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."FRIENDSHIP"

ALTER TABLE "DB2ADMIN"."FRIENDSHIP" 
	ADD CONSTRAINT "CC1364706567365" PRIMARY KEY
		("FRIENDNAME",
		 "USERNAME");


------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."GAME_REQ"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."GAME_REQ"  (
		  "USER1" VARCHAR(20) NOT NULL , 
		  "USER2" VARCHAR(20) NOT NULL , 
		  "IS_TIMED" CHAR(1) NOT NULL WITH DEFAULT '0' , 
		  "MOVE_TIMER" CHAR(10) , 
		  "REQ_ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +0  
		    INCREMENT BY +1  
		    MINVALUE +0  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."GAME_REQ"

ALTER TABLE "DB2ADMIN"."GAME_REQ" 
	ADD CONSTRAINT "CC1364723652073" PRIMARY KEY
		("REQ_ID");


ALTER TABLE "DB2ADMIN"."GAME_REQ" ALTER COLUMN "REQ_ID" RESTART WITH 64;

------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."ADMIN"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."ADMIN"  (
		  "ADMIN_ID" VARCHAR(20) NOT NULL , 
		  "ADMIN_PASSWORD" VARCHAR(35) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."ADMIN"

ALTER TABLE "DB2ADMIN"."ADMIN" 
	ADD CONSTRAINT "CC1364834473804" PRIMARY KEY
		("ADMIN_ID");


------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."TOURNAMENT_REQ"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."TOURNAMENT_REQ"  (
		  "REQ_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "T_ID" BIGINT NOT NULL , 
		  "USERNAME" VARCHAR(10) NOT NULL , 
		  "STATUS" CHAR(1) NOT NULL WITH DEFAULT 0 )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."TOURNAMENT_REQ"

ALTER TABLE "DB2ADMIN"."TOURNAMENT_REQ" 
	ADD CONSTRAINT "CC1365437518704" PRIMARY KEY
		("REQ_ID");


ALTER TABLE "DB2ADMIN"."TOURNAMENT_REQ" ALTER COLUMN "REQ_ID" RESTART WITH 40;

------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."GROUPS"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."GROUPS"  (
		  "GROUP_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "TOURNAMENT_ID" BIGINT NOT NULL , 
		  "LEADING_PLAYER" VARCHAR(20) , 
		  "NO_OF_MEMBERS" INTEGER )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."GROUPS"

ALTER TABLE "DB2ADMIN"."GROUPS" 
	ADD CONSTRAINT "CC1365476818909" PRIMARY KEY
		("GROUP_ID");


ALTER TABLE "DB2ADMIN"."GROUPS" ALTER COLUMN "GROUP_ID" RESTART WITH 2744;

------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."TOURNAMENT_GAMES"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."TOURNAMENT_GAMES"  (
		  "TOURNAMENT_ID" BIGINT NOT NULL , 
		  "GAME_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "END_DATE" DATE , 
		  "RECORD" XML , 
		  "GROUP_ID" BIGINT , 
		  "ROUND" CHAR(1) )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."TOURNAMENT_GAMES"

ALTER TABLE "DB2ADMIN"."TOURNAMENT_GAMES" 
	ADD CONSTRAINT "CC1365599181911" PRIMARY KEY
		("GAME_ID");


ALTER TABLE "DB2ADMIN"."TOURNAMENT_GAMES" ALTER COLUMN "GAME_ID" RESTART WITH 33;

------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."CHESS_GAME"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."CHESS_GAME"  (
		  "GAME_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "RECORD" XML NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."CHESS_GAME"

ALTER TABLE "DB2ADMIN"."CHESS_GAME" 
	ADD CONSTRAINT "CC1365073263729" PRIMARY KEY
		("GAME_ID");


ALTER TABLE "DB2ADMIN"."CHESS_GAME" ALTER COLUMN "GAME_ID" RESTART WITH 49;

------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."WINNERS"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."WINNERS"  (
		  "TOURNAMENT_ID" BIGINT NOT NULL , 
		  "WINNER" VARCHAR(20) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."WINNERS"

ALTER TABLE "DB2ADMIN"."WINNERS" 
	ADD CONSTRAINT "CC1365762482602" PRIMARY KEY
		("WINNER",
		 "TOURNAMENT_ID");


------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."GROUP_MEMBERS"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."GROUP_MEMBERS"  (
		  "GROUP_ID" BIGINT NOT NULL , 
		  "MEMBER" VARCHAR(20) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."GROUP_MEMBERS"

ALTER TABLE "DB2ADMIN"."GROUP_MEMBERS" 
	ADD CONSTRAINT "CC1365762803708" PRIMARY KEY
		("GROUP_ID",
		 "MEMBER");


------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."TOURNAMENT"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."TOURNAMENT"  (
		  "TOURNAMENT_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    NO CACHE  
		    NO ORDER ) , 
		  "NAME" VARCHAR(50) NOT NULL , 
		  "START_DATE" DATE NOT NULL , 
		  "END_DATE" DATE NOT NULL , 
		  "MAX_PLAYERS" INTEGER , 
		  "CASHPRIZE" INTEGER )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."TOURNAMENT"

ALTER TABLE "DB2ADMIN"."TOURNAMENT" 
	ADD CONSTRAINT "CC1365318302802" PRIMARY KEY
		("TOURNAMENT_ID");


ALTER TABLE "DB2ADMIN"."TOURNAMENT" ALTER COLUMN "TOURNAMENT_ID" RESTART WITH 3;

------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."TOURNAMENT_POINTS"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."TOURNAMENT_POINTS"  (
		  "TOURNAMENT_ID" BIGINT NOT NULL , 
		  "USERNAME" VARCHAR(20) NOT NULL , 
		  "POINTS" INTEGER WITH DEFAULT 0 , 
		  "GROUP_ID" BIGINT NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."TOURNAMENT_POINTS"

ALTER TABLE "DB2ADMIN"."TOURNAMENT_POINTS" 
	ADD CONSTRAINT "CC1365769586542" PRIMARY KEY
		("TOURNAMENT_ID",
		 "USERNAME");


------------------------------------------------
-- DDL Statements for table "DB2ADMIN"."USER"
------------------------------------------------
 

CREATE TABLE "DB2ADMIN"."USER"  (
		  "USERNAME" VARCHAR(20) NOT NULL , 
		  "EMAIL" VARCHAR(30) NOT NULL , 
		  "PASSWORD" VARCHAR(35) NOT NULL , 
		  "FNAME" VARCHAR(20) NOT NULL , 
		  "LNAME" VARCHAR(20) NOT NULL , 
		  "DOB" DATE , 
		  "COUNTRY" VARCHAR(30) , 
		  "MOBILE_NO" VARCHAR(10) , 
		  "GENDER" CHAR(1) , 
		  "DESC" VARCHAR(100) , 
		  "NO_OF_GAMES_PLAYED" INTEGER NOT NULL WITH DEFAULT '0' , 
		  "NO_OF_GAMES_WON" INTEGER NOT NULL WITH DEFAULT '0' , 
		  "NO_OF_GAMES_DRAWN" INTEGER NOT NULL WITH DEFAULT '0' , 
		  "NO_OF_TOUR_PLAYED" INTEGER NOT NULL WITH DEFAULT '0' , 
		  "NO_OF_TOUR_WON" INTEGER NOT NULL WITH DEFAULT '0' , 
		  "RATING" INTEGER NOT NULL WITH DEFAULT 1200 , 
		  "IS_VERIFIED" CHAR(1) NOT NULL WITH DEFAULT '0' , 
		  "LAST_REQUEST_TIMESTAMP" TIMESTAMP , 
		  "IS_LOGGEDIN" CHAR(1) NOT NULL WITH DEFAULT '0' )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2ADMIN"."USER"

ALTER TABLE "DB2ADMIN"."USER" 
	ADD CONSTRAINT "CC1364312776930" PRIMARY KEY
		("USERNAME");


-- DDL Statements for unique constraints on Table "DB2ADMIN"."USER"


ALTER TABLE "DB2ADMIN"."USER" 
	ADD CONSTRAINT "CC1364312790955" UNIQUE
		("EMAIL");

-- DDL Statements for foreign keys on Table "DB2ADMIN"."ACTIVATION"

ALTER TABLE "DB2ADMIN"."ACTIVATION" 
	ADD CONSTRAINT "CC1364470094157" FOREIGN KEY
		("USERNAME")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."FRIENDSHIP"

ALTER TABLE "DB2ADMIN"."FRIENDSHIP" 
	ADD CONSTRAINT "CC1364706610543" FOREIGN KEY
		("FRIENDNAME")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."FRIENDSHIP" 
	ADD CONSTRAINT "CC1364706623673" FOREIGN KEY
		("USERNAME")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."GAME_REQ"

ALTER TABLE "DB2ADMIN"."GAME_REQ" 
	ADD CONSTRAINT "CC1364723667644" FOREIGN KEY
		("USER1")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."GAME_REQ" 
	ADD CONSTRAINT "CC1364723759599" FOREIGN KEY
		("USER2")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."TOURNAMENT_REQ"

ALTER TABLE "DB2ADMIN"."TOURNAMENT_REQ" 
	ADD CONSTRAINT "CC1365437522003" FOREIGN KEY
		("T_ID")
	REFERENCES "DB2ADMIN"."TOURNAMENT"
		("TOURNAMENT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."TOURNAMENT_REQ" 
	ADD CONSTRAINT "CC1365437528352" FOREIGN KEY
		("USERNAME")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."GROUPS"

ALTER TABLE "DB2ADMIN"."GROUPS" 
	ADD CONSTRAINT "CC1365476822919" FOREIGN KEY
		("TOURNAMENT_ID")
	REFERENCES "DB2ADMIN"."TOURNAMENT"
		("TOURNAMENT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."TOURNAMENT_GAMES"

ALTER TABLE "DB2ADMIN"."TOURNAMENT_GAMES" 
	ADD CONSTRAINT "CC1365599337365" FOREIGN KEY
		("TOURNAMENT_ID")
	REFERENCES "DB2ADMIN"."TOURNAMENT"
		("TOURNAMENT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."TOURNAMENT_GAMES" 
	ADD CONSTRAINT "CC1365599364899" FOREIGN KEY
		("GROUP_ID")
	REFERENCES "DB2ADMIN"."GROUPS"
		("GROUP_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."WINNERS"

ALTER TABLE "DB2ADMIN"."WINNERS" 
	ADD CONSTRAINT "CC1365762496042" FOREIGN KEY
		("TOURNAMENT_ID")
	REFERENCES "DB2ADMIN"."TOURNAMENT"
		("TOURNAMENT_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."WINNERS" 
	ADD CONSTRAINT "CC1365762531736" FOREIGN KEY
		("WINNER")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."GROUP_MEMBERS"

ALTER TABLE "DB2ADMIN"."GROUP_MEMBERS" 
	ADD CONSTRAINT "CC1365762810137" FOREIGN KEY
		("GROUP_ID")
	REFERENCES "DB2ADMIN"."GROUPS"
		("GROUP_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."GROUP_MEMBERS" 
	ADD CONSTRAINT "CC1365762857069" FOREIGN KEY
		("MEMBER")
	REFERENCES "DB2ADMIN"."USER"
		("USERNAME")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2ADMIN"."TOURNAMENT_POINTS"

ALTER TABLE "DB2ADMIN"."TOURNAMENT_POINTS" 
	ADD CONSTRAINT "CC1365599756322" FOREIGN KEY
		("TOURNAMENT_ID")
	REFERENCES "DB2ADMIN"."TOURNAMENT"
		("TOURNAMENT_ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2ADMIN"."TOURNAMENT_POINTS" 
	ADD CONSTRAINT "CC1365837879398" FOREIGN KEY
		("GROUP_ID")
	REFERENCES "DB2ADMIN"."GROUPS"
		("GROUP_ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;








-- DDL Statements for Public Synonym

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_ALL_TABLES" FOR TABLE "SYSIBMADM"."ALL_ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_ARGUMENTS" FOR TABLE "SYSIBMADM"."ALL_ARGUMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_CATALOG" FOR TABLE "SYSIBMADM"."ALL_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_COL_COMMENTS" FOR TABLE "SYSIBMADM"."ALL_COL_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_CONSTRAINTS" FOR TABLE "SYSIBMADM"."ALL_CONSTRAINTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_CONS_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_CONS_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_DEPENDENCIES" FOR TABLE "SYSIBMADM"."ALL_DEPENDENCIES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_ERRORS" FOR TABLE "SYSIBMADM"."ALL_ERRORS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_INDEXES" FOR TABLE "SYSIBMADM"."ALL_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_IND_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_IND_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_IND_PARTITIONS" FOR TABLE "SYSIBMADM"."ALL_IND_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_OBJECTS" FOR TABLE "SYSIBMADM"."ALL_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PART_INDEXES" FOR TABLE "SYSIBMADM"."ALL_PART_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PART_KEY_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_PART_KEY_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PART_TABLES" FOR TABLE "SYSIBMADM"."ALL_PART_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PROCEDURES" FOR TABLE "SYSIBMADM"."ALL_PROCEDURES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_SEQUENCES" FOR TABLE "SYSIBMADM"."ALL_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_SOURCE" FOR TABLE "SYSIBMADM"."ALL_SOURCE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_SYNONYMS" FOR TABLE "SYSIBMADM"."ALL_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TABLES" FOR TABLE "SYSIBMADM"."ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_COL_STATISTICS" FOR TABLE "SYSIBMADM"."ALL_TAB_COL_STATISTICS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_COMMENTS" FOR TABLE "SYSIBMADM"."ALL_TAB_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PARTITIONS" FOR TABLE "SYSIBMADM"."ALL_TAB_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PRIVS" FOR TABLE "SYSIBMADM"."ALL_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PRIVS_MADE" FOR TABLE "SYSIBMADM"."ALL_TAB_PRIVS_MADE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PRIVS_RECD" FOR TABLE "SYSIBMADM"."ALL_TAB_PRIVS_RECD";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TRIGGERS" FOR TABLE "SYSIBMADM"."ALL_TRIGGERS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_VIEWS" FOR TABLE "SYSIBMADM"."ALL_VIEWS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_VIEW_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_VIEW_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."CAT" FOR TABLE "SYSIBMADM"."USER_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."COLS" FOR TABLE "SYSIBMADM"."USER_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ALL_TABLES" FOR TABLE "SYSIBMADM"."DBA_ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ARGUMENTS" FOR TABLE "SYSIBMADM"."DBA_ARGUMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_CATALOG" FOR TABLE "SYSIBMADM"."DBA_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_COL_COMMENTS" FOR TABLE "SYSIBMADM"."DBA_COL_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_CONSTRAINTS" FOR TABLE "SYSIBMADM"."DBA_CONSTRAINTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_CONS_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_CONS_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_DEPENDENCIES" FOR TABLE "SYSIBMADM"."DBA_DEPENDENCIES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ERRORS" FOR TABLE "SYSIBMADM"."DBA_ERRORS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_INDEXES" FOR TABLE "SYSIBMADM"."DBA_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_IND_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_IND_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_IND_PARTITIONS" FOR TABLE "SYSIBMADM"."DBA_IND_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_OBJECTS" FOR TABLE "SYSIBMADM"."DBA_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PART_INDEXES" FOR TABLE "SYSIBMADM"."DBA_PART_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PART_KEY_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_PART_KEY_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PART_TABLES" FOR TABLE "SYSIBMADM"."DBA_PART_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PROCEDURES" FOR TABLE "SYSIBMADM"."DBA_PROCEDURES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ROLES" FOR TABLE "SYSIBMADM"."DBA_ROLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ROLE_PRIVS" FOR TABLE "SYSIBMADM"."DBA_ROLE_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SEQUENCES" FOR TABLE "SYSIBMADM"."DBA_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SOURCE" FOR TABLE "SYSIBMADM"."DBA_SOURCE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SYNONYMS" FOR TABLE "SYSIBMADM"."DBA_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SYS_PRIVS" FOR TABLE "SYSIBMADM"."DBA_SYS_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TABLES" FOR TABLE "SYSIBMADM"."DBA_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TABLESPACES" FOR TABLE "SYSIBMADM"."DBA_TABLESPACES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_COL_STATISTICS" FOR TABLE "SYSIBMADM"."DBA_TAB_COL_STATISTICS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_COMMENTS" FOR TABLE "SYSIBMADM"."DBA_TAB_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_PARTITIONS" FOR TABLE "SYSIBMADM"."DBA_TAB_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_PRIVS" FOR TABLE "SYSIBMADM"."DBA_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TRIGGERS" FOR TABLE "SYSIBMADM"."DBA_TRIGGERS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_VIEWS" FOR TABLE "SYSIBMADM"."DBA_VIEWS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_VIEW_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_VIEW_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DICT" FOR TABLE "SYSIBMADM"."DICTIONARY";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DICTIONARY" FOR TABLE "SYSIBMADM"."DICTIONARY";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DICT_COLUMNS" FOR TABLE "SYSIBMADM"."DICT_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."IND" FOR TABLE "SYSIBMADM"."USER_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."OBJ" FOR TABLE "SYSIBMADM"."USER_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ROLE_ROLE_PRIVS" FOR TABLE "SYSIBMADM"."ROLE_ROLE_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ROLE_SYS_PRIVS" FOR TABLE "SYSIBMADM"."ROLE_SYS_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ROLE_TAB_PRIVS" FOR TABLE "SYSIBMADM"."ROLE_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SEQ" FOR TABLE "SYSIBMADM"."USER_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SESSION_PRIVS" FOR TABLE "SYSIBMADM"."SESSION_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SESSION_ROLES" FOR TABLE "SYSIBMADM"."SESSION_ROLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SIN" FOR TABLE "SYSIBMADM"."USER_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."TAB" FOR TABLE "SYSIBMADM"."TAB";

CREATE PUBLIC ALIAS "SYSPUBLIC"."TABS" FOR TABLE "SYSIBMADM"."USER_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ALL_TABLES" FOR TABLE "SYSIBMADM"."USER_ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ARGUMENTS" FOR TABLE "SYSIBMADM"."USER_ARGUMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_CATALOG" FOR TABLE "SYSIBMADM"."USER_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_COL_COMMENTS" FOR TABLE "SYSIBMADM"."USER_COL_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_CONSTRAINTS" FOR TABLE "SYSIBMADM"."USER_CONSTRAINTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_CONS_COLUMNS" FOR TABLE "SYSIBMADM"."USER_CONS_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_DEPENDENCIES" FOR TABLE "SYSIBMADM"."USER_DEPENDENCIES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ERRORS" FOR TABLE "SYSIBMADM"."USER_ERRORS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_INDEXES" FOR TABLE "SYSIBMADM"."USER_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_IND_COLUMNS" FOR TABLE "SYSIBMADM"."USER_IND_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_IND_PARTITIONS" FOR TABLE "SYSIBMADM"."USER_IND_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_OBJECTS" FOR TABLE "SYSIBMADM"."USER_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PART_INDEXES" FOR TABLE "SYSIBMADM"."USER_PART_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PART_KEY_COLUMNS" FOR TABLE "SYSIBMADM"."USER_PART_KEY_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PART_TABLES" FOR TABLE "SYSIBMADM"."USER_PART_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PROCEDURES" FOR TABLE "SYSIBMADM"."USER_PROCEDURES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ROLE_PRIVS" FOR TABLE "SYSIBMADM"."USER_ROLE_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SEQUENCES" FOR TABLE "SYSIBMADM"."USER_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SOURCE" FOR TABLE "SYSIBMADM"."USER_SOURCE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SYNONYMS" FOR TABLE "SYSIBMADM"."USER_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SYS_PRIVS" FOR TABLE "SYSIBMADM"."USER_SYS_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TABLES" FOR TABLE "SYSIBMADM"."USER_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TABLESPACES" FOR TABLE "SYSIBMADM"."USER_TABLESPACES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_COLUMNS" FOR TABLE "SYSIBMADM"."USER_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_COL_STATISTICS" FOR TABLE "SYSIBMADM"."USER_TAB_COL_STATISTICS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_COMMENTS" FOR TABLE "SYSIBMADM"."USER_TAB_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PARTITIONS" FOR TABLE "SYSIBMADM"."USER_TAB_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PRIVS" FOR TABLE "SYSIBMADM"."USER_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PRIVS_MADE" FOR TABLE "SYSIBMADM"."USER_TAB_PRIVS_MADE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PRIVS_RECD" FOR TABLE "SYSIBMADM"."USER_TAB_PRIVS_RECD";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TRIGGERS" FOR TABLE "SYSIBMADM"."USER_TRIGGERS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_VIEWS" FOR TABLE "SYSIBMADM"."USER_VIEWS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_VIEW_COLUMNS" FOR TABLE "SYSIBMADM"."USER_VIEW_COLUMNS";


---------------------------------------
-- Authorization statement on table space 
---------------------------------------

 
GRANT USE OF TABLESPACE "SYSTOOLSTMPSPACE" TO  PUBLIC   ;

COMMIT WORK;

CONNECT RESET;

TERMINATE;

-- Generate statistics for all creators 
-- Creating DDL for table(s)
;