/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-04-16 16:22:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import databasepools.*;
import java.sql.*;

public final class game_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "check_session.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


    String username=(String)session.getAttribute("username");
    c3p0pooledconnection c  = new c3p0pooledconnection() ;
	Connection conn = c.create() ;
	String game_id=request.getParameter("game_id");
	HttpSession se=request.getSession(false);
	se.setAttribute("game_id",game_id);
	
	String query1="xquery db2-fn:sqlquery(\"select record from db2admin.chess_game  where game_id = '"+game_id+"'\")/game/whiteplayer/text()";
	String query2="xquery db2-fn:sqlquery(\"select record from db2admin.chess_game  where game_id = '"+game_id+"'\")/game/blackplayer/text()";
	String query3="xquery db2-fn:sqlquery(\"select record from db2admin.chess_game  where game_id = '"+game_id+"'\")/game/pgn/text()";
	String query4="select XMLQUERY('$RECORD/game/isend/text()') from chess_game where game_id = '"+game_id+"'";
	
	PreparedStatement stmt1=null,stmt2=null,stmt3=null,stmt4=null;
	ResultSet rs1=null,rs2=null,rs3=null,rs4=null;
	String white="",black="",pgn="",isend="";
	boolean is_white=false; 
	boolean is_black=false;

	
	try {
		
        stmt1=conn.prepareStatement(query1);
        stmt2=conn.prepareStatement(query2);
        stmt3=conn.prepareStatement(query3);
        stmt4=conn.prepareStatement(query4);

        			
        		rs1=stmt1.executeQuery();
        		rs2=stmt2.executeQuery();
        		rs3=stmt3.executeQuery();
        		rs4=stmt4.executeQuery();
        		
        		rs3.next();
        		rs4.next();
        	
        						
        		if(!rs1.next() || !rs2.next() )
        		{	
        			
        			response.sendRedirect("status.jsp");	
        		}
        		else
        		{
        			white=rs1.getString(1);
        			black=rs2.getString(1);
        			pgn=rs3.getString(1);
        			isend=rs4.getString(1);
        			
        			
        			is_white=white.equals(username); 
        			is_black=black.equals(username);


        			if(!is_white && !is_black)
        			{
        				response.sendRedirect("status.jsp");
        			}
        		}
        				
        		
		}
		 
		
	catch (Exception exc) {
		// TODO Auto-generated catch block
		exc.printStackTrace();
	}


    
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>Chess Masters Club</title>\r\n");
      out.write("<link href=\"stylesheets/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" media=\"all\" href=\"stylesheets/blue.css\" id=\"theme_css\" />\r\n");
      out.write("<script src=\"javascript/chess.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"javascript/chess.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"javascript/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"javascript/game.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Header -->\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("    \r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("\t\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "session.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- top navigation -->\r\n");
      out.write("\t\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"game_play.jsp\" >Game Play</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"tutorial.jsp\" >Tutorials</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"tournaments.jsp\" >Tournaments</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"faq.jsp\" >FAQs</a></li>   \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\t\t\t<!-- banner message and building background -->\r\n");
      out.write("\t\t\t<div id=\"banner\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("                An Online Chess Club where game lovers can learn and play Chess games with their friends or other players. \r\n");
      out.write("                </p> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("            \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div id=\"gameid\"  style=\"visibility:hidden;\">");
      out.print( game_id );
      out.write("</div>\r\n");
      out.write("<div id=\"pgn\"  style=\"visibility:hidden;\">");
      out.print( pgn );
      out.write("</div>\r\n");
      out.write("<div id=\"wb\"  style=\"visibility:hidden;\">\r\n");
 
if(is_white) out.print("w");
else if(is_black) out.print("b");

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Main Content -->\r\n");
      out.write("\t<div id=\"main\" class=\"container\" >\r\n");
      out.write("\t \r\n");
      out.write("    \r\n");
      out.write("     <!-- left column -->\r\n");
      out.write("\t\t<div style=\"float:left; font-size:14px; margin-right:40px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h2 style=\"font-size:16px;\"> White Player:</h2>\r\n");
      out.write("\t\t\t<div id=\"whiteplayer\" align=\"center\" style=\" background-color:#eee;\">");
      out.print( white );
      out.write("</div>\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t<h2 style=\"font-size:16px;\">Black Player:</h2>\r\n");
      out.write("\t\t\t<div id=\"blackplayer\" align=\"center\" style=\" background-color:#eee;\">");
      out.print( black );
      out.write("</div>\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h2 style=\"font-size:16px;\">Customize Board:</h2>\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"theme\" checked=\"checked\"    value=\"blue\" onclick=\"theme(this);\" />Blue Theme<br />\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"theme\" onclick=\"theme(this);\" value=\"sand\" />Sand Theme<br />\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"theme\"   value=\"grey\" onclick=\"theme(this);\"/>Grey Theme<br />\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"theme\"  value=\"green\" onclick=\"theme(this);\" />Green Theme<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h2 style=\"font-size:16px;\"> Who's Turn:</h2>\r\n");
      out.write("\t\t\t<div id=\"turn\" align=\"center\" style=\" background-color:#eee;font-size:20px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t&#9812;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br /><br />\r\n");
      out.write("\t\t\t<h2 style=\"font-size:16px;\" >Captures so far:</h2><br />\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h3>Captures by Black:</h3>\r\n");
      out.write("\t\t\t\t<div id=\"bcapturelist\" style=\" background-color:#eee;font-size:20px; \">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<br/>\r\n");
      out.write("\t\t\t\t<h3>Captures by White: </h3>\r\n");
      out.write("\t\t\t\t<div id=\"wcapturelist\"  style=\" background-color:#eee;font-size:20px; \">\r\n");
      out.write("             \t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- main content area -->\r\n");
      out.write("\t\t<div id=\"center\">\r\n");
      out.write("\t\t<div class=\"article_wrapper\" style=\"margin-left:auto; margin-right:auto; margin-bottom:60px; \">\r\n");
      out.write("\t\t\t<div id=\"status1\" align=\"center\" style=\"color:#900; margin-left:50px;font-weight:bold; font-size:25px;\">\r\n");
      out.write("\t\t\t");

				if(isend.matches("1"))
				out.print("Game over!");
			
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<br />\t\r\n");
      out.write("<table id=\"chess_board\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("        <td id=\"c8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h8\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h7\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h6\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h5\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h4\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h3\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h2\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id=\"a1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"b1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"c1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"d1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"e1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"f1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"g1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t<td id=\"h1\" onclick=\"javascript:checkmove(this.id)\"><div></div></td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<br />\r\n");
      out.write("<div id=\"status\" align=\"center\" style=\"color:#900; margin-left:50px;font-weight:bold; font-size:25px;\">\r\n");

	if(isend.matches("1"))
	out.print("Game over!");

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- right column -->\r\n");
      out.write("\t\t<div style=\"float:right; font-size:14px; margin-left: 20px;\">\r\n");
      out.write("\t\t");


		if(isend.matches("0"))
		{
			
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form action=\"ResignGame\" method=\"post\">\r\n");
      out.write("\t\t<input id=\"button\" style=\"padding: 2px 5px;\" type=\"submit\" value=\"Resign Game\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"gameid\" value=\"");
      out.print( game_id );
      out.write("\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<input type=\"checkbox\" id=\"highlight\" value=\"highlight\" /> Prompt Moves\r\n");
      out.write("\t\t<br /><br />\r\n");
      out.write("\t\t<div id=\"possible\" style=\"font-size:15px; color:#900; background-color:#eee; \" ></div>\t\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\tPromote To:\r\n");
      out.write("\t\t\t<select id=\"promotion\" name=\"promotion\">\r\n");
      out.write("\t\t\t<option value='q'>Queen</option>\r\n");
      out.write("\t\t\t<option value='n'>Knight</option>\r\n");
      out.write("\t\t\t<option value='b'>Bishop</option>\r\n");
      out.write("\t\t\t<option value='r'>Rook</option>\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h3 style=\"font-size:16px; \" >Moves so far:</h3><br />\r\n");
      out.write("\t\t\t<div id=\"movelist\" style=\"background-color:#eee;\">\r\n");
      out.write("             </div>\r\n");
      out.write("             <br />\r\n");
      out.write("             <input id=\"button\" type=\"button\" value=\"Export to PGN\" onclick=\"cmcpgn();\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        \r\n");
      out.write("     </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.html", out, false);
      out.write("\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
