/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-04-16 16:19:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import databasepools.*;
import java.util.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" >\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>Chess Masters Club</title>\r\n");
      out.write("<link href=\"stylesheets/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Header -->\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("    \r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("\t\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "session.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- top navigation -->\r\n");
      out.write("\t\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"game_play.jsp\" >Game Play</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"tutorial.jsp\" >Tutorials</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"tournaments.jsp\" >Tournaments</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"faq.jsp\" >FAQs</a></li>   \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\t\t\t<!-- banner message and building background -->\r\n");
      out.write("\t\t\t<div id=\"banner\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("                An Online Chess Club where game lovers can learn and play Chess games with their friends or other players. \r\n");
      out.write("                </p> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("            \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");

Date date_time=new Date();
SimpleDateFormat dnow=new SimpleDateFormat("yyyy-MM-dd");
String dt=dnow.format(date_time);

Calendar now = Calendar.getInstance();
now.add(Calendar.MINUTE, -30);
SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
String n=df.format(now.getTime());

String username=(String)session.getAttribute("username");
String query="select * from tournament where start_date>'"+dt+"'";
String query1="select username,rating from user order by rating desc limit 8";
String query2="select f.friendname from friendship as f inner join user as u on f.friendname=u.username "
				+"where f.username='"+username+"' and f.status='1' and u.is_loggedin='1' and u.last_request_timestamp>'"+n+"'"
				+"union "
				+"select f.username from friendship as f inner join user as u on f.username=u.username "
				+"where f.friendname='"+username+"' and f.status='1' and u.is_loggedin='1' and u.last_request_timestamp>'"+n+"'";
c3p0pooledconnection c = new c3p0pooledconnection() ;
Connection conn = c.create() ;
PreparedStatement ps=null;
ResultSet rs=null;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Main Content -->\r\n");
      out.write("\t<div id=\"main\" class=\"container\">\r\n");
      out.write("\t\t<!-- left column -->\r\n");
      out.write("\t\t<div id=\"leftcolumn\">\r\n");
      out.write("\t\t\t<h3 class=\"leftbox\">Online Friends</h3>\r\n");
      out.write("\t\t\t<ul class=\"leftbox borderedlist\">\r\n");
      out.write("\t\t\t ");

			 
			  ps=conn.prepareStatement(query2);
			 // ps.setString(1, username);
			 // ps.setString(2, username);
			  rs=ps.executeQuery();
			  //System.out.println(query2);
			  int flag=0;
		while(rs.next())
		{
			
			String friend=rs.getString(1);
			flag=1;
			 
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"profile.jsp?username=");
      out.print( friend );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print( friend );
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t");

		}
		if(flag==0)
		{
			 
      out.write("\r\n");
      out.write("\t\t\t\t<li>No online friends found.</li>\r\n");
      out.write("\t\t\t\t");

		}
				
      out.write("\r\n");
      out.write("           </ul>\r\n");
      out.write("\t\t\t  <hr />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- main content area -->\r\n");
      out.write("\t\t<div id=\"center\">\r\n");
      out.write("\t\t\t<div class=\"article_wrapper\">\r\n");
      out.write("\t\t\t\t<h2>Chess is the Gymnasium of the Mind</h2>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\r\n");
      out.write("Chess is variously described as a science, an art and a sport. It has the virtue of being completely free of the element of luck: the result of each game depends entirely upon the skill of the players. \r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Chess helps develop critical thinking; logic, reasoning and problem solving abilities; memory, concentration and visualization skills; confidence; patience; determination and good sportsmanship. </p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Memory Improvement-\r\n");
      out.write("\r\n");
      out.write("The nature of the game is such that the visual aspects of the game (positional \r\n");
      out.write("configurations, anticipated piece movements, diagonals, ranks, files, etc.) \r\n");
      out.write("make deep impressions on that area of the mind which is responsible for \r\n");
      out.write("memory. It should also be noted that recall is \r\n");
      out.write("also improved. Chess is definitely an \r\n");
      out.write("excellent memory exerciser the effects of which are transferable to other \r\n");
      out.write("subjects where memory is necessary. \r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Logic- \r\n");
      out.write("\r\n");
      out.write("The kind of logic \r\n");
      out.write("employed in chess is based largely upon the rule schema, but not entirely. \r\n");
      out.write("Player \"A\" may choose a move not because it is most logical, \r\n");
      out.write("but because he believes that player \"B\" will not see the reason behind it. \r\n");
      out.write("Many chess players have asserted that chess either \r\n");
      out.write("sharpened or created a unique sense of logic which they have applied to \r\n");
      out.write("other aspects of life successfully. \r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("Observation and Analysis-\r\n");
      out.write("\r\n");
      out.write("Chess has the unique ability of teaching the player to become aware of details \r\n");
      out.write("and the nuances of every position. The player learns to observe the whole \r\n");
      out.write("board and recognize both the important and unimportant aspects of the position \r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write(" \r\n");
      out.write("Chess is a marvelous game. It teaches skills that can help in various facets of life.\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("We learn by chess the habit of not being discouraged by present bad appearances in the state of our affairs, the habit of hoping for a favorable change, and that of persevering in search of resources. - Benjamin Franklin\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      out.write("\r\n");
      out.write("So have fun with chess and persevere to be a great chess player, for\r\n");
      out.write("\r\n");
      out.write("\"Every Chess master was once a beginner.\"  -  Irving Chernev\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<!-- right column -->\r\n");
      out.write("\t\t<div id=\"rightcolumn\" >\r\n");
      out.write("\t\t\t<h3 class=\"leftbox\">Upcoming Tournaments</h3>\r\n");
      out.write("\t\t\t<ul class=\"leftbox borderedlist\">\r\n");
      out.write("\t\t\t");

			  ps=conn.prepareStatement(query);
		      rs=ps.executeQuery();
		flag=0;
		while(rs.next())
		{
			flag=1;
			String id=rs.getString(1);
			String name=rs.getString(2);
			String sd=rs.getString(3);				
			String ed=rs.getString(4);
			  
      out.write("\r\n");
      out.write("\t\t\t\t<li style=\"margin-bottom: 15px; font-size: 12px;\">\r\n");
      out.write("\t\t\t\t<a href=\"tournament.jsp?t_id=");
 out.print(id); 
      out.write("\" style=\"color : #000; font-size: 15px;\">");
 out.print(name); 
      out.write("</a>\r\n");
      out.write("\t\t\t\tStart Date : ");
 out.print(sd); 
      out.write("<br />\r\n");
      out.write("\t\t\t\tEnd Date : ");
 out.print(ed); 
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

		}
				if(flag==0)
		{
			 
      out.write("\r\n");
      out.write("\t\t\t\t<li>There are no upcoming Tournaments.</li>\r\n");
      out.write("\t\t\t\t");

		}
				
      out.write("\r\n");
      out.write("           </ul>\r\n");
      out.write("\t\t\t  <hr />\r\n");
      out.write("\t\t\t\r\n");
      out.write("              <h3 class=\"leftbox\">Top Players</h3>\r\n");
      out.write("\t\t\t<ul class=\"leftbox borderedlist\">\r\n");
      out.write("\t\t\t  ");

			  ps=conn.prepareStatement(query1);
		      rs=ps.executeQuery();
		while(rs.next())
		{
			String player=rs.getString(1);
			String rating=rs.getString(2);
			  
      out.write("\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t\t<li style=\"margin-bottom: 15px; font-size: 12px;\">\r\n");
      out.write("\t\t\t\t<a href=\"profile.jsp?username=");
      out.print( player );
      out.write("\" style=\"color : #000; font-size: 15px;\">");
      out.print( player );
      out.write("</a>\r\n");
      out.write("\t\t\t\tRating : ");
      out.print( rating );
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");

		}
				
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("\t\t\t  <hr />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.html", out, false);
      out.write("\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
