/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2013-04-16 16:20:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import databasepools.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

public final class my_005fgames_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "check_session.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>Chess Masters Club</title>\r\n");
      out.write("<link href=\"stylesheets/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Header -->\r\n");
      out.write("\t<div id=\"header\">\r\n");
      out.write("    \r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("            \r\n");
      out.write("\t\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "session.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t<!-- top navigation -->\r\n");
      out.write("\t\t\t<ul id=\"navigation\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li  class=\"active\"><a href=\"game_play.jsp\" >Game Play</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"tutorial.jsp\" >Tutorials</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"tournaments.jsp\" >Tournaments</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"faq.jsp\" >FAQs</a></li>   \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t<!-- banner message and building background -->\r\n");
      out.write("\t\t\t<div id=\"banner\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("                An Online Chess Club where game lovers can learn and play Chess games with their friends or other players. \r\n");
      out.write("                </p>  \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<hr />     \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- Start Main Content -->\r\n");
      out.write("\t<div id=\"main\" class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- main content area -->\r\n");
      out.write("\t\t<div id=\"center\" >\r\n");
      out.write("\t\t\t<div class=\"article_wrapper\"  style=\"min-height: 550px;\" >\r\n");
      out.write("\t\t\t<h2 style=\"padding:0px 0px 0px 80px;\">My Games</h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			String user=(String)session.getAttribute("username");

		
			if(user==null) 
			{
				 request.getRequestDispatcher("/index.jsp").forward(request, response);
			}
			c3p0pooledconnection c = new c3p0pooledconnection() ;
			Connection conn = c.create() ;
			PreparedStatement ps =null,ps2=null;
			ResultSet rs=null,rs2=null;
			String query1="select game_id,XMLQUERY('$RECORD/game/lastmovedt/text()'),XMLQUERY('$RECORD/game/date/text()'),XMLQUERY('$RECORD/game/whiteplayer/text()') , XMLQUERY('$RECORD/game/blackplayer/text()'),XMLQUERY('$RECORD/game/isend/text()'),XMLQUERY('$RECORD/game/winner/text()') from chess_game order by game_id desc";
			String query2="select game_id,XMLQUERY('$RECORD/game/lastmovedt/text()'),XMLQUERY('$RECORD/game/date/text()'),XMLQUERY('$RECORD/game/whiteplayer/text()') , XMLQUERY('$RECORD/game/blackplayer/text()'),XMLQUERY('$RECORD/game/isend/text()'),XMLQUERY('$RECORD/game/winner/text()'),tournament_id from tournament_games order by game_id desc";
			Date date_time=new Date();
			SimpleDateFormat dnow=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
			String dtnow=dnow.format(date_time);
			try {
				   ps=conn.prepareStatement(query1);
			       rs=ps.executeQuery();	
			       
			       
      out.write("\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t       <table id=\"signup\" cellpadding=\"15px;\" style= \"margin-bottom: 70px;\">\t\t\r\n");
      out.write("    \t\t\t\r\n");
      out.write("\t<tr style=\"font-size: 16px; font-weight: bold;\">\r\n");
      out.write("\t\t<td>White Player</td>\r\n");
      out.write("\t\t<td>Black Player</td>\r\n");
      out.write("\t\t<td>Started On</td>\r\n");
      out.write("\t\t<td>Last Moved Date</td>\r\n");
      out.write("\t\t<td>Status</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t       ");

					
    			while(rs.next())
		        		{	
    						String game_id=rs.getString(1);
		     				String wp=rs.getString(4);
		     				String bp=rs.getString(5);
		     				String dt=rs.getString(3);
		     				String lmdt=rs.getString(2);
		     				String end=rs.getString(6);
		     				if(user.matches(wp) || user.matches(bp))
		     				{
		     				
      out.write("\t\t\t\t\r\n");
      out.write("\t\t     \t\t\t\t\t\r\n");
      out.write("\t\t     <tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td><a href=\"profile.jsp?username=");
 out.print(wp); 
      out.write('"');
      out.write('>');
 out.print(wp); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"profile.jsp?username=");
 out.print(bp); 
      out.write('"');
      out.write('>');
 out.print(bp); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td>");
 out.print(dt); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
 out.print(lmdt); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
 if(end.equals("0"))out.print("Ongoing"); 
				else 
					{
					out.print("Completed:"); 
					String winner=rs.getString(7);
					if(winner.matches("White")) out.print("White won");
					else if(winner.matches("Black")) out.print("Black won");
						else out.print("Game draw");
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"game.jsp?game_id=");
 out.print(game_id); 
      out.write('"');
      out.write('>');
 if(end.equals("0"))out.print("Continue Playing"); else out.print("View Game"); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t\t");

		     				}
		        	}
		
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");

			
			}
				 
				
			catch (Exception exc) {
				// TODO Auto-generated catch block
				exc.printStackTrace();
			}
			
      out.write("\r\n");
      out.write("\t\t\t<h2 style=\"padding:0px 0px 0px 80px;\">My Tournaments</h2>\r\n");
      out.write("\t\t\t");

			try {
				   ps=conn.prepareStatement(query2);
			       rs=ps.executeQuery();	
			       
			       
      out.write("\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t       <table id=\"signup\" cellpadding=\"15px;\" style= \"margin-bottom: 70px;\">\t\t\r\n");
      out.write(" \t\t\t\r\n");
      out.write("\t<tr style=\"font-size: 16px; font-weight: bold;\">\r\n");
      out.write("\t\t<td>Tournament Name</td>\r\n");
      out.write("\t\t<td>White Player</td>\r\n");
      out.write("\t\t<td>Black Player</td>\r\n");
      out.write("\t\t<td>Last Moved Date</td>\r\n");
      out.write("\t\t<td>Status</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t\t       \r\n");
      out.write("\t\t\t       ");

			       
 			while(rs.next())
		        		{	
 						String game_id=rs.getString(1);
		     				String wp=rs.getString(4);
		     				String bp=rs.getString(5);
		     				String name="";
		     				String lmdt=rs.getString(2);
		     				String end=rs.getString(6);
		     				String tid=rs.getString(8);
		     				String query3="select name from tournament where tournament_id='"+tid+"'";
		 			        PreparedStatement s=conn.prepareStatement(query3);	
		 			        ResultSet r=s.executeQuery();
		 			        if(r.next())
		 			        {
		 			        	name=r.getString(1);
		 			        }
		     				if(user.matches(wp) || user.matches(bp))
		     				{
		     				
      out.write("\t\t\t\t\r\n");
      out.write("\t\t     \t\t\t\t\t\r\n");
      out.write("\t\t     <tr>\r\n");
      out.write("\t\t\t\t<td><a href=\"tournament.jsp?t_id=");
 out.print(tid); 
      out.write('"');
      out.write('>');
 out.print(name); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"profile.jsp?username=");
 out.print(wp); 
      out.write('"');
      out.write('>');
 out.print(wp); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t<td><a href=\"profile.jsp?username=");
 out.print(bp); 
      out.write('"');
      out.write('>');
 out.print(bp); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td>");
 out.print(lmdt); 
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
 if(end.equals("0"))out.print("Ongoing"); 
				else 
					{
					out.print("Completed:"); 
					String winner=rs.getString(7);
					if(winner.matches("White")) out.print("White won");
					else if(winner.matches("Black")) out.print("Black won");
						else out.print("Game draw");
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"t_game.jsp?game_id=");
 out.print(game_id); 
      out.write('"');
      out.write('>');
 if(end.equals("0"))out.print("Continue Playing"); else out.print("View Game"); 
      out.write("</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t \t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t");

		     				}
		        	}
		
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t");

			
			}
				 
				
			catch (Exception exc) {
				// TODO Auto-generated catch block
				exc.printStackTrace();
			}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- right column -->\r\n");
      out.write("\t\t<div id=\"rightcolumn\" style=\"float: right;\">\r\n");
      out.write("\t\t<h3 class=\"leftbox\"><a href=\"smartmatch.jsp\">Smart Match</a></h3>\r\n");
      out.write("\t\t\t  <hr />\r\n");
      out.write("\t\t\t  <h3 class=\"leftbox\"><a href=\"game_play.jsp\">Search by Username</a></h3>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("            <h3 class=\"leftbox\"><a href=\"friend_game_req.jsp\">Play With a Friend</a></h3>\r\n");
      out.write("\t\t\t  <hr />\r\n");
      out.write("\t\t\t <h3 class=\"leftbox\"><a href=\"pending_game_request.jsp\">Pending Game Requests</a></h3>\r\n");
      out.write("\t\t\t<hr />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Start Footer -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.html", out, false);
      out.write("\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
